### ISSUE TITLE
please make all-codecs+ variant

### ISSUE THREAD

**Issue by megapro17** [RobRich999/Chromium_Clang#10]
avx2+fma to be exact
with h265, amr, etc support

**Comment by megapro17** [comment]
Also, is it really chromium was build by clang? exeinfo says abous microsoft c++
![image](https://user-images.githubusercontent.com/16743370/80122326-0ee99880-8596-11ea-949b-13cf1506daa3.png)

**Comment by woolyss** [comment]
Clang is the compiler used to build Chromium.
Official info: https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#setting-up-windows

The support of h265 is not necessary because websites does not (and will does not) use them.
The favorite video codec for the present and future is AV1.

https://caniuse.com/#feat=av1
Free codec supported by Google, Mozilla, Netflix, Microsoft, Intel, Amazon, Vimeo, Twitch, Facebook...

https://caniuse.com/#feat=h.265
Proprietary codec only supported by Apple

**Comment by megapro17** [comment]
> You can find **AVX2** builds at https://github.com/RobRich999/Chromium_Clang/tags

I indeed downloaded a build from link `avx2+fma | Win64 experimental`, and this tool says nothing about clang

>The support of h265/hevc is not necessary because websites does not (and will does not) use them.

I know, but why not, other builds have this support, from Marmaduke

**Comment by woolyss** [comment]
> his tool says nothing about clang
Because clang-cl is used from inside Visual Studio.
https://clang.llvm.org/docs/UsersManual.html#clang-cl
https://clang.llvm.org/docs/MSVCCompatibility.html

> why not, other builds have this support, from Marmaduke
h.265 codecs support is normally reserved for Chromium OS and not officially supported by the Chromium browser. https://www.chromium.org/audio-video
Marmaduke is a developper liking experiments ;)

**Comment by RobRich999** [comment]
As a very late followup, clang-cl is largely a drop-in replacement for msvc. ;)

**Comment by megapro17** [comment]
What
