### ISSUE TITLE
New updated patch of Cromite browser Add new patch of Cromite browser to make possible to enable energy battery saver feature even when plugged in 

### ISSUE THREAD

**Issue by trimechee** [RobRich999/Chromium_Clang#42]
Hello, thank you very much for the new version of Chromium-Clang brwoser ! 💯 🥇 

It seems that Cromite Browser in the last update has achieved the sensational extraordinary great feat of making the "energy battery saver" option active by default even when plugged in even without battery on a desktop computer in order to preserve our battery and energy and the ecology and avoid fan noisy and expensive electricity bill.... We hope Winchrome browser will be able to implement this option even when plugged in because this battery saver option is disabled when plugged in Winchrome browser, thank you so much .

build/patches/WIN-enable-HighEfficiencyMode-by-default.patch

https://github.com/uazo/cromite/commit/0dc5d37 https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/performance_manager/user_tuning/battery_saver_mode_manager.cc https://chromium-review.googlesource.com/c/chromium/src/+/5046375 https://issues.chromium.org/issues/40158973 https://bugs.chromium.org/p/chromium/issues/detail?id=1153154&no_tracker_redirect=1

**Comment by RobRich999** [comment]
He subsequently disabled the feature due to security fingerprinting concerns.

"It disables battery mode by default, being a mechanism that can be used as a fingerpriting bit."

Source: https://github.com/uazo/cromite/issues/728

Realistically, I suspect it would be better for overall system power efficiency to tune a heavily restricted OS power profile.

For even finer grained control, have you looked at the Process Laso utility? I sometimes used it back in the day on Windows build systems. It can set per app and/or per process CPU priorities, CPU affinities, memory priorities, I/O priorities, power profiles, efficiency mode (EcoQOS if supported), and more. You can set at idle power plans as well.

https://bitsum.com/

About EcoQOS:

https://devblogs.microsoft.com/performance-diagnostics/introducing-ecoqos/

**Comment by trimechee** [comment]
Hello, it seems i am unfairly shadow banned with my new account so i repost ma response : 

"Hello Mr @RobRich999 , I'm trimechee, sorry for the delay because I'm not connected with my other account...

Ohhh awesome fantastic !! Thank you very much for these valuable tips and precious tricks :) 💯 🥇

Yes I discovered that this patch does not have the desired effect when I did not see an option in the performance section and the developer himself confirmed this to me and that what he implemented is the opposite of my wish.....

Recently i discovered some tricks and flags to more economize battery and power :

add shortcut

--enable-features=UseEcoQoSForBackgroundProcess --enable-low-end-device-mode

chrome:flags
disable :
smooth scrolling
Auto-disable Accessibility

chrome://flags/#memory-saver-multi-state-mode
Enable the multi-state option for Memory Saver Mode

chrome://version to see if the command line flag is there

disable webassembly, webrtc, webgl......"
