### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by insilications** [RobRich999/Chromium_Clang#7]
Just want to thank you for these builds, specially the ones with avx2 and whole program optimization. If I could I would tip or pay a coffee to you. Have a nice day.

**Comment by RobRich999** [comment]
Welcome. :)

Wish I could update the AVX2 builds more often, but those currently are being done on a comparatively slow quad-core system due to my primary 32-core build box running Opterons with only AVX support,

That said, AVX2 builds actually might offer no significant benefit or even be slower on AVX2-compatible hardware, especially depending upon how the proc handles 128b vs 256b AVX2 instructions. I know AVX and AVX2 builds perform about the same on my Kaby Lake notebook.

**Comment by megapro17** [comment]
How can I test is avx2 version is faster? I ran some benchmark and it was higher score on avx2

**Comment by RobRich999** [comment]
https://www.browserbench.org/ is a good place to start for basic browser benchmarking. :)

Also AVX2 ideally should help some with media codecs, encryption, etc. Testing those is not as straightforward, though.

**Comment by megapro17** [comment]
Yeah exact this benchmark I used. avx2 was a bit faster. 
I want to ask, can you build chromium with h.265 support? Or it is also called all-codecs+.
