### ISSUE TITLE
[avx/avx2] Video playback question

### ISSUE THREAD

**Issue by fuu1** [RobRich999/Chromium_Clang#9]
Unlike in other chromium variants AVX/AVX2 versions seem to stop video playback while out of focus (audio playback remains).

Is this behavior intended? If yes is there a way to prevent that?
I made a quick video to showcase what i mean.

Showcase Video: [Video Playback](https://streamable.com/w7dvr)

Its easy reproduce by using task view or task preview.

**Comment by RobRich999** [comment]
I can not think of anything optimization related to cause the issue.

There used to be about:flags for background, focus, etc. of video, but most of them have been deprecated as the features were natively enabled over recent years.

It could be a long shot, but try changing this current flag to disabled:

chrome://flags/#enable-audio-focus-enforcement

Otherwise try disabling hardware acceleration as a test. 

Of note you also can replicate the PiP feature with a Google-provided extension. I can verify it works for my current AVX2 build, as I just tested it.

https://github.com/RobRich999/Chromium_Clang/releases/tag/v82.0.4061.0-r741948-win64-avx2

**Comment by fuu1** [comment]
A change in settings has no impact on the mentioned behavior.

This is on a Kaby Lake processor if this information is relevant.

**Comment by RobRich999** [comment]
Curious, what happens if changing the graphics backend to D3D9? OpenGL?

chrome://flags/#use-angle

**Comment by fuu1** [comment]
Changing graphics backend has no impact.

**Comment by RobRich999** [comment]
Sadly, no idea here.

Ultimately, there is a not a substantial performance difference between my SSE2 and AVX builds, so I suggest opting for the SSE2 builds for now.

I try to keep those two builds relatively in sync when it comes to build options, optimization levels, etc. I just do not blanket enable AVX for all optimized source code on SSE2 builds. Of note, even when it comes to the SSE2 builds, specific components directly targeting AVX, AVX2, etc. can still use those SIMD instruction sets when processor support is detected.
